-- V3: Seed development data
-- Passwords are PBKDF2-SHA256 of "password123"
-- (generated by the backend; these are example hashes — app will re-hash on register)

-- Insert dev users using MD5 placeholder — real auth goes through the API.
-- Use the /auth/register endpoint instead for actual dev setup.
-- This seed just creates the group chat and settings scaffolding.

DO $$
DECLARE
    alice_id  BIGINT;
    bob_id    BIGINT;
    carol_id  BIGINT;
    chat1_id  BIGINT;
    chat2_id  BIGINT;
BEGIN
    -- Users (passwords will be set via API or seeder script)
    INSERT INTO users (username, email, password_hash, display_name)
    VALUES ('alice', 'alice@example.com', 'SEED_PLACEHOLDER', 'Alice')
    ON CONFLICT DO NOTHING
    RETURNING id INTO alice_id;

    IF alice_id IS NULL THEN
        SELECT id INTO alice_id FROM users WHERE username = 'alice';
    END IF;

    INSERT INTO users (username, email, password_hash, display_name)
    VALUES ('bob', 'bob@example.com', 'SEED_PLACEHOLDER', 'Bob')
    ON CONFLICT DO NOTHING
    RETURNING id INTO bob_id;

    IF bob_id IS NULL THEN
        SELECT id INTO bob_id FROM users WHERE username = 'bob';
    END IF;

    INSERT INTO users (username, email, password_hash, display_name)
    VALUES ('carol', 'carol@example.com', 'SEED_PLACEHOLDER', 'Carol')
    ON CONFLICT DO NOTHING
    RETURNING id INTO carol_id;

    IF carol_id IS NULL THEN
        SELECT id INTO carol_id FROM users WHERE username = 'carol';
    END IF;

    -- User settings
    INSERT INTO user_settings (user_id) VALUES (alice_id) ON CONFLICT DO NOTHING;
    INSERT INTO user_settings (user_id) VALUES (bob_id)   ON CONFLICT DO NOTHING;
    INSERT INTO user_settings (user_id) VALUES (carol_id) ON CONFLICT DO NOTHING;

    -- Group chat
    INSERT INTO chats (type, name, owner_id)
    VALUES ('group', 'Dev Team', alice_id)
    ON CONFLICT DO NOTHING
    RETURNING id INTO chat1_id;

    IF chat1_id IS NOT NULL THEN
        INSERT INTO chat_members (chat_id, user_id, role) VALUES
            (chat1_id, alice_id,  'owner'),
            (chat1_id, bob_id,    'member'),
            (chat1_id, carol_id,  'member')
        ON CONFLICT DO NOTHING;
    END IF;

END $$;
